# Created by trellis-cli v1.11.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  bozbalci.me:
    site_hosts:
    - canonical: bozbalci.me
      redirects:
      - www.bozbalci.me
    local_path: ../site
    branch: main
    repo: git@github.com:bozbalci/bozbalci.me.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
